var point_videoJSON = {
        "type": "FeatureCollection",
        "name": "snettisham_aerial_tour_point",
        "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
        "features": [
        { "type": "Feature", "properties": { "ID": "D", "Location": "Long Lake to Headwaters", "video_file": "IMG_8823", "Name": "Long Lake to Headwaters", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.810898011802294, 58.192828323206577 ] } },
        { "type": "Feature", "properties": { "ID": "E", "Location": "Upper Long River to Long Lake Headwaters to Long Lake", "video_file": "IMG_8832", "Name": "Upper Long River to Long Lake Headwaters to Long Lake", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.713389258607606, 58.16192528831531 ] } },
        { "type": "Feature", "properties": { "ID": "F", "Location": "Long Lake Dam", "video_file": "IMG_8833", "Name": "Long Lake Dam", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.774747627275588, 58.191930807904463 ] } },
        { "type": "Feature", "properties": { "ID": "G", "Location": "Upper Long River to Indian Lake to Lower Long River", "video_file": "IMG_8834", "Name": "Upper Long River to Indian Lake to Lower Long River", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.70324592498099, 58.165376536301245 ] } },
        { "type": "Feature", "properties": { "ID": "H", "Location": "Upper Speel River to Barrier Falls to Lower Speel River to Tidewaters", "video_file": "IMG_8835", "Name": "Upper Speel River to Barrier Falls to Lower Speel River to Tidewaters", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.633293421562996, 58.196317825139793 ] } },
        { "type": "Feature", "properties": { "ID": "I", "Location": "Lower Speel River to Speel Lake up to Barrier Falls", "video_file": "IMG_8836", "Name": "Lower Speel River to Speel Lake up to Barrier Falls", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.608029342022888, 58.20180327063126 ] } },
        { "type": "Feature", "properties": { "ID": "J", "Location": "Lower Speel River to Tidewaters", "video_file": "IMG_8845", "Name": "Lower Speel River to Tidewaters", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.616394406388395, 58.174890033475123 ] } },
        { "type": "Feature", "properties": { "ID": "K", "Location": "Glacier Creek to Headwaters", "video_file": "IMG_8831", "Name": "Glacier Creek to Headwaters", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.729036972773287, 58.14621189040728 ] } },
        { "type": "Feature", "properties": { "ID": "L", "Location": "Tailrace Hatchery to Other Facilities", "video_file": "IMG_8830", "Name": "Tailrace Hatchery to Other Facilities", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.7367895337498, 58.140473794226203 ] } },
        { "type": "Feature", "properties": { "ID": "A", "Location": "Crater Creek to Crater lake", "video_file": "IMG_8827", "Name": "Crater Creek to Crater lake", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.771762538221793, 58.137333853105552 ] } },
        { "type": "Feature", "properties": { "ID": "B", "Location": "Crater Lake Headwaters to Crater Creek", "video_file": "IMG_8826", "Name": "Crater Lake Headwaters to Crater Creek", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.835111364701788, 58.130135466857752 ] } },
        { "type": "Feature", "properties": { "ID": "C", "Location": "Crater Lake to Headwaters", "video_file": "IMG_8825", "Name": "Crater Lake to Headwaters", "youtube": "<iframe width=\"300\" height=\"300\" src=\"https://www.youtube.com/embed/6baK-Iz0IKg?si=UiW_Fk4UJq_RcibJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"" }, "geometry": { "type": "Point", "coordinates": [ -133.829569167762202, 58.13346374558099 ] } }
        ]
        }
